---

mentions:
  - '@ddg'
  - '@DDG'
  - '@duck'
  - '@quack'
  - '@mallard'

color: dark_teal

ratelimit:
  queries: 2
  per_seconds: 10
  log: ratelimit_violations.csv

bot:
  username: MyGreatBot#1000
  token: 'MMMMMMMMMMMMMMMMMMMMMMMM.AAAAAA.BBBBBBBBBBBBBBBBBBBBBBBBBBB'
